apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-identity-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-identity-demo
  template:
    metadata:
      labels:
        app: workload-identity-demo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: workload-identity-sa
      containers:
      - name: demo
        image: mcr.microsoft.com/azure-cli:latest
        command:
          - /bin/bash
          - -c
          - |
            echo ""
            echo "Workload Identity Demo"
            echo "======================"
            echo ""
            echo "Environment variables:"
            env | grep AZURE
            echo ""
            echo "Attempting to log in using Workload Identity..."
            az identity show --ids ${WORKLOAD_IDENTITY_CLIENT_ID} -o tsv
            az login --identity --client-id ${WORKLOAD_IDENTITY_CLIENT_ID}
            echo ""
            echo "Attempting to get access token using federated token..."
            az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID
            # az account get-access-token --query accessToken --output tsv
            echo ""
            echo "Attempting to list storage containers..."
            az storage container list --account-name ${STORAGE_ACCOUNT_NAME} --auth-mode login
            echo ""
            echo "Sleeping to keep container running..."
            sleep infinity
        env:
        - name: STORAGE_ACCOUNT_NAME
          value: ${STORAGE_ACCOUNT_NAME}
        - name: WORKLOAD_IDENTITY_CLIENT_ID
          value: ${WORKLOAD_IDENTITY_CLIENT_ID}
